### ISSUE TITLE
ImportError: cannot import name 'PINYIN'

### ISSUE THREAD

**Issue by handbye** [RicterZ/genpAss#28]
```
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from genpass import VERSION, __author__, __email__
  File "D:\haker\0-tools\04-密码相关\genpAss\genpass\__init__.py", line 11, in <module>
    from .lib.person import Person
  File "D:\haker\0-tools\04-密码相关\genpAss\genpass\lib\person.py", line 5, in <module>
    from genpass import generator
  File "D:\haker\0-tools\04-密码相关\genpAss\genpass\generator.py", line 4, in <module>
    from config import PINYIN
ImportError: cannot import name 'PINYIN'
```

**Comment by darkMoon1973** [comment]
将包导入方式改为绝对路径导入便可

`../genpAss/genpass/__init__.py` 包导入修改：
```python
# coding=utf-8

VERSION = '0.2.1'
__author__ = 'ricter'
__email__ = 'ricterzheng@gmail.com'

import genpass.rules
import genpass.command
import genpass.config
import genpass.lib
from .lib.person import Person
from .lib.pinyin import PinYin

__all__ = ['rules', 'command', 'config', 'lib', 'VERSION', '__author__', '__email__', 'Person', 'PinYin']

```

`../genpAss/genpass/generator.py`  包导入修改
```python
# coding=utf-8
from genpass.lib.pinyin import PinYin
from genpass.lib.constants import SEQUENCES
from genpass.config import PINYIN
```
then 
`python setup.py install`
